version: "3"

tasks:
  create-cluster:
    cmds:
      - k3d cluster create --config k3d-config.yaml

  label-workers:
    cmds:
      - kubectl get nodes -o name | grep agent | xargs -P 4 -I {} kubectl label {} node-role.kubernetes.io/agent=

  initial-setup:
    cmds:
      - task: create-cluster
      - task: label-workers

  apply-terraform:
    cmds:
      - terraform -chdir=infra init
      - terraform -chdir=infra apply

  cleanup:
    cmds:
      - k3d cluster delete mpi
